server:
   port: 9000
#
spring:
  data:
    mongodb:
      host: ds145667.mlab.com
      port: 45667
      uri: mongodb://heroku_zn26j1t7:test123@ds145667.mlab.com:45667/heroku_zn26j1t7

    mongo:
      repositories.enabled: true


